# -*- coding: utf-8 -*-
"""Genera docs/GUIA_IMPLEMENTACION_FUNCIONAL.md.

Es la guia operativa del Funcional: cada etapa con lo que hace, donde lo hace,
COMO COMPRUEBA que quedo bien, y que sale mal si no.

Se diferencia de MANUAL_DESPLIEGUE en que aquel dice QUE hay que poner -y trae
la ficha de las 28 tablas- y este dice COMO se procede y COMO SE VERIFICA cada
etapa antes de pasar a la siguiente.

Uso:  python scripts/generar_guia_funcional.py
"""
import os
import sys

RAIZ = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(RAIZ, "scripts"))
import modelo_objetivo
from modelo_objetivo import MODELO, REGLAS, CLAVE_GENERADA, RETIRADAS, CAMPOS_RETIRADOS

# El modelo describe datos, no interfaz. Se comprueba al generar, no se afirma
# de memoria.
INTERFAZ = [n for n in ("VISTAS", "ACCIONES", "SLICES") if hasattr(modelo_objetivo, n)]
N_RETIRADAS = sum(len(v) for v in CAMPOS_RETIRADOS.values())

REFS = [(t, c["nombre"], c["ref"], bool(c.get("es_parte_de")))
        for t, d in MODELO.items() for c in d["columnas"] if c.get("ref")]
N_REF = len(REFS)
N_PART = sum(1 for r in REFS if r[3])

L = []
w = L.append

w("# Guia de implementacion — el Funcional, paso a paso")
w("")
w("**Como se procede en cada etapa y como se comprueba antes de pasar a la siguiente.**")
w("")
w("> **Escrita por rol.** El **Funcional** es quien configura AppSheet sin programar. Esta guia se")
w("> replica en otro contrato cambiando solo los nombres de tablas.")
w("")
w("| | |")
w("|---|---|")
w("| Que dice esta guia | **Como** se hace cada etapa y **como se verifica** |")
w("| Que dice `MANUAL_DESPLIEGUE.md` | **Que** hay que poner: la ficha de las %d tablas, columna por columna |" % len(MODELO))
w("| Fuente | `scripts/modelo_objetivo.py`. Esta guia se genera de ahi |")
w("")
w("## Como usar esta guia")
w("")
w("**Cada etapa termina con una comprobacion.** Si no pasa, no siga: el error se multiplica en la")
w("siguiente y despues cuesta el triple encontrarlo.")
w("")
w("**Anote lo que va comprobando.** Al final hay un acta que rellenar. Este proyecto tiene tres")
w("cierres reportados que no resistieron la comprobacion contra el archivo, y las tres veces lo paro")
w("un script, no una persona.")
w("")
w("**Si algo no sale como dice esta guia, pare y reportelo.** Eso es informacion, no un fallo suyo:")
w("cada cosa rara que ha aparecido en este proyecto acabo siendo un comportamiento de AppSheet que")
w("nadie habia documentado.")
w("")
w("---")
w("")

# ---------------------------------------------------------------- ETAPA 0
w("# Etapa 0 — Antes de abrir AppSheet")
w("")
w("**Duracion:** 15 minutos. **Sin esto, todo lo demas hereda el error.**")
w("")
w("### 0.1 Copia de seguridad de la hoja")
w("")
w("En Google Sheets: *Archivo -> Hacer una copia*. Nombrela con la fecha.")
w("")
w("**Es lo unico que no se recupera.** Todo lo demas vive en el repositorio y se regenera.")
w("")
w("### 0.2 Comprobar que ninguna pestana este oculta")
w("")
w("En Google Sheets, abajo a la izquierda: el icono de las cuatro lineas, *Todas las hojas*. Las")
w("ocultas salen en gris.")
w("")
w("**AppSheet ignora las pestanas ocultas y no avisa.** Ocho catalogos estaban ocultos y la")
w("aplicacion cargaba 24 tablas de 32 sin un solo mensaje. Se perdieron dos dias en eso.")
w("")
w("### 0.3 Verificar el archivo")
w("")
w("Descargue el libro —*Archivo -> Descargar -> Microsoft Excel*—, guardelo en `BD/` y ejecute:")
w("")
w("```bash")
w('python scripts/verificar_faseA.py "BD/<su archivo>.xlsx"')
w("```")
w("")
w("### COMPROBACION de la etapa 0")
w("")
w("| Que | Como se ve que esta bien |")
w("|---|---|")
w("| Copia hecha | Existe en el Drive, con la fecha en el nombre |")
w("| Pestanas visibles | El menu *Todas las hojas* no muestra ninguna en gris |")
w("| Archivo verificado | El script imprime **`FASE A CERRADA`** |")
w("")
w("> **Si dice `FASE A INCOMPLETA`, pare.** El mensaje dice exactamente que falta. `F-18` avisa de")
w("> pestanas ocultas y `F-19` de columnas declaradas que ya no existen.")
w("")

# ---------------------------------------------------------------- ETAPA 1
w("# Etapa 1 — Crear la aplicacion")
w("")
w("**Duracion:** 5 minutos.")
w("")
w("### 1.1")
w("")
w("En AppSheet: **Create -> App -> Start with existing data**. Elija el documento de **Google")
w("Sheets**.")
w("")
w("> **No suba un `.xlsx`.** Si la aplicacion lee un archivo subido, queda mirando una foto fija y")
w("> nada se sincroniza. Tiene que apuntar al documento vivo.")
w("")
w("### 1.2 Quien la crea, la posee")
w("")
w("**Un coautor no puede dar de alta tablas**, y toda esta guia consiste en eso. Cree la aplicacion")
w("con la cuenta que va a operarla.")
w("")
w("### COMPROBACION de la etapa 1")
w("")
w("| Que | Como se ve |")
w("|---|---|")
w("| La fuente es el Sheets vivo | *Data -> [tabla] -> Source Type* dice `Sheets` |")
w("| Usted es propietario | *Data -> `+` -> Add data* **no** dice «As a co-author...» |")
w("")

# ---------------------------------------------------------------- ETAPA 2
w("# Etapa 2 — Dar de alta las %d tablas" % len(MODELO))
w("")
w("**Duracion:** 45 minutos. Es lo mas repetitivo de todo.")
w("")
w("### 2.1 Una por una, y en orden")
w("")
w("*Data -> `+` -> Add data -> el Sheets -> la pestana*.")
w("")
w("**El orden importa y no es alfabetico.** Determina que referencias infiere AppSheet solo al dar")
w("de alta cada tabla. La lista esta en `MANUAL_DESPLIEGUE.md` paso 2.")
w("")
w("### 2.2 Las %d que el modelo retira" % len(RETIRADAS))
w("")
w("```")
w(" · ".join("`%s`" % t for t in sorted(RETIRADAS)))
w("```")
w("")
w("**Sobre la hoja vigente ya no existen**, porque la hoja se genera del modelo: no van a aparecer en")
w("el desplegable. La lista sirve para reconocerlas si algun dia trabaja sobre una copia antigua del")
w("libro. **No lo de por hecho, compruebelo:**")
w("")
w("```bash")
w('python -c "import openpyxl;n=openpyxl.load_workbook(\'BD/Modelo_Datos_PLANTILLA.xlsx\','
  "read_only=True).sheetnames;print([t for t in %s if t in n])\"" % sorted(RETIRADAS))
w("```")
w("")
w("Tiene que devolver `[]`. Y los bancos de preguntas que tres de ellas guardaban **ya estan dentro")
w("de `FRM_Preguntas`**, que es el motor unico.")
w("")
w("### COMPROBACION de la etapa 2")
w("")
w("| Que | Como se ve |")
w("|---|---|")
w("| Son exactamente %d | Cuentelas en *Data -> Tables* |" % len(MODELO))
w("| Ninguna duplicada | Ningun nombre acaba en `_1`, `(2)` ni empieza por `Copy of` |")
w("| Cada una a su pestana | Abra la ficha de cada una y lea el *Qualifier* |")
w("| Las %d retiradas no estan | %s no aparecen |"
  % (len(RETIRADAS), ", ".join("`%s`" % t for t in sorted(RETIRADAS))))
w("")
w("> **La duplicada es el fallo tipico de esta etapa.** Si el borrado no se confirma y el alta si,")
w("> AppSheet crea una segunda tabla sobre la misma pestana. **Las referencias se reparten entre las")
w("> dos y la mitad de las filas parece desaparecer, sin error.**")
w("")

# ---------------------------------------------------------------- ETAPA 3
w("# Etapa 3 — Las claves")
w("")
w("**Duracion:** 30 minutos. **Es lo unico que no se recupera despues.**")
w("")
w("### 3.1 Por que importa tanto")
w("")
w("Al dar de alta una tabla, AppSheet elige clave por su cuenta: examina las columnas de izquierda a")
w("derecha buscando valores unicos y, **si ninguna le sirve, combina dos en una clave compuesta**.")
w("")
w("**Contra una clave compuesta no resuelve ninguna referencia.** Y el sintoma no es un mensaje: es")
w("que la etapa 5 entera falla sin decir por que.")
w("")
w("### 3.2 Que hacer en cada tabla")
w("")
w("*Data -> Columns*. Una sola casilla `KEY` marcada, sobre la columna correcta, **tipo `Text`**.")
w("")
w("La lista de las %d claves esta en `MANUAL_DESPLIEGUE.md` paso 3." % len(MODELO))
w("")
w("### 3.3 Por que todas `Text` y no `Number`")
w("")
w("`USR_Usuarios.UsuarioID` tiene un valor alfanumerico entre otros numericos. **Si AppSheet infiere")
w("`Number`, esa fila se queda sin clave valida y ese usuario deja de existir para el sistema.**")
w("")
w("### 3.4 Clave automatica para filas nuevas")
w("")
w("Estas %d tablas crean filas desde la aplicacion. Sin `Initial value = UNIQUEID()` no sabe que" % len(CLAVE_GENERADA))
w("identificador poner:")
w("")
w("```")
for t in sorted(CLAVE_GENERADA):
    pk = [c["nombre"] for c in MODELO[t]["columnas"] if c.get("pk")]
    if pk:
        w("%-24s %s" % (t, pk[0]))
w("```")
w("")
w("### COMPROBACION de la etapa 3")
w("")
w("| Que | Como se ve |")
w("|---|---|")
w("| Una sola `KEY` por tabla | Recorra las %d. Si hay dos marcadas, quite la sobrante |" % len(MODELO))
w("| Ninguna compuesta | Si el editor muestra la clave como combinacion de columnas, corrijala |")
w("| Todas `Text` | Ninguna en `Number` |")
w("| Las %d con `UNIQUEID()` | Compruebe el `Initial value` de cada una |" % len(CLAVE_GENERADA))
w("")

# ---------------------------------------------------------------- ETAPA 4
w("# Etapa 4 — Los tipos que AppSheet no adivina")
w("")
w("**Duracion:** 20 minutos.")
w("")
w("Todo llega de una hoja de calculo, asi que entra como texto o numero. La lista completa esta en")
w("`MANUAL_DESPLIEGUE.md` paso 4.")
w("")
w("### La que no se puede fallar")
w("")
w("```")
w("MAN_Mantenimientos.Coordenadas_Cierre_LatLong  ->  LatLong")
w("```")
w("")
w("**Sobre ella se monta el geofencing, y `DISTANCE()` no funciona sobre texto.** Si esta columna")
w("queda como `Text`, la regla de la etapa 7 no se puede ni escribir.")
w("")
w("### Las cuatro marcas de tiempo")
w("")
w("```")
w("MAN_Mantenimientos.FechaHoraRegistro   ->  ChangeTimestamp")
w("FOT_Fotografias.FechaHora              ->  ChangeTimestamp")
w("FIR_Firmas.FechaHora                   ->  ChangeTimestamp")
w("NOV_Novedades.FechaHora                ->  ChangeTimestamp")
w("```")
w("")
w("**`ChangeTimestamp` la pone el servidor.** Un `Initial value = NOW()` lo pone el telefono, y el")
w("usuario puede cambiar la hora del telefono. **Sin esto, la hora de cada fotografia y de cada firma")
w("no prueba nada** — que es justo lo que el sistema existe para sostener.")
w("")
w("### COMPROBACION de la etapa 4")
w("")
w("| Que | Como se ve |")
w("|---|---|")
w("| `Coordenadas_Cierre_LatLong` | Tipo `LatLong` |")
w("| Las cuatro marcas | Tipo `ChangeTimestamp` |")
w("| Las imagenes y la firma | `Image` y `Signature`, no `Text` |")
w("| Los `Enum` | Con sus valores declarados, no vacios |")
w("")

# ---------------------------------------------------------------- ETAPA 5
w("# Etapa 5 — Las %d referencias" % N_REF)
w("")
w("**Duracion:** 1 hora. Es el corazon del sistema.")
w("")
w("### 5.1 La regla de la que sale todo")
w("")
w("> **Una referencia guarda el valor de la clave de la tabla destino.**")
w("")
w("De ahi que el orden importe: **primero la clave del destino, despues quien la apunta**. La lista")
w("en orden esta en `MANUAL_DESPLIEGUE.md` paso 5.")
w("")
w("### 5.2 Cuidado con las listas de otros documentos")
w("")
w("Circulo una lista de **15** referencias por convertir, y era correcta para lo que normaba: una")
w("aplicacion existente donde otras 23 ya estaban puestas. Ese documento esta retirado.")
w("**Construyendo desde cero son %d.** Si al terminar cuenta 15, siguio la lista equivocada." % N_REF)
w("")
w("### 5.3 `IsPartOf` va en %d, y en ninguna mas" % N_PART)
w("")
w("```")
for t, c, dest, part in REFS:
    if part:
        w("%-34s -> %s" % (t + "." + c, dest))
w("```")
w("")
w("**`MAN_Mantenimientos.OTID` va DESMARCADO, y es deliberado.** Con `IsPartOf`, borrar una orden")
w("borraria su ejecucion, sus fotografias y su firma **en cascada**.")
w("")
w("### 5.4 Despues de cada conversion, mire la tabla")
w("")
w("**Convertir a `Ref` conserva solo las filas cuyo valor coincide con la clave del destino. Las")
w("demas quedan huerfanas sin mensaje de error**: la celda se queda en blanco.")
w("")
w("### COMPROBACION de la etapa 5")
w("")
w("| Que | Como se ve |")
w("|---|---|")
w("| Son %d | Cuente las columnas de tipo `Ref` en todas las tablas |" % N_REF)
w("| Ninguna rota | El indicador `!` de referencia rota. **Hay que ir a mirarlo: no se anuncia** |")
w("| Sin blancos nuevos | Ninguna celda vacia donde antes habia un valor |")
w("| `IsPartOf` en %d | Y desmarcado en `MAN_Mantenimientos.OTID` |" % N_PART)
w("")
w("**Y la prueba de la cadena**, en el Asistente de Expresiones sobre `MAN_Mantenimientos`:")
w("")
w("```")
w("[OTID].[ActivoID].[Ubicacion_LatLong]")
w("[OTID].[TecnicoID].[Correo]")
w("```")
w("")
w("Las dos en verde. **Se cierra sin dar a `Done`.**")
w("")
w("> **Nunca pruebe una expresion escribiendola dentro de una columna.** Ya ocurrio: quedo una")
w("> `App formula` escribiendo la coordenada del activo dentro de una columna retirada, y una")
w("> `App formula` **escribe en la hoja** cada vez que se modifica la fila.")
w("")

# ---------------------------------------------------------------- ETAPA 6
w("# Etapa 6 — RETIRADA. No la haga")
w("")
w("**Duracion: 0.** Se conserva numerada para que quien tenga una copia antigua de esta guia sepa que")
w("este trabajo salio del plan, y no crea que se le olvido.")
w("")
w("Esta etapa mandaba ocultar, una por una, las %d columnas que el modelo no declara, mas las tres que" % N_RETIRADAS)
w("AppSheet convertia en `Ref` sola por coincidencia de nombre. **Todas ellas venian de un libro")
w("heredado. La hoja vigente se genera del modelo y no trae ninguna**, asi que no hay nada que")
w("esconder ni ninguna referencia que deshacer.")
w("")
w("**Compruebelo usted, no lo de por bueno:**")
w("")
w("```bash")
w('python scripts/verificar_faseA.py "BD/Modelo_Datos_PLANTILLA.xlsx"')
w("```")
w("")
w("Entre los conformes tiene que salir esta linea, que es la regla `F-19`:")
w("")
w("```")
w("ok Hoja limpia: ninguna de las %d columnas retiradas existe ya. No hay nada que ocultar" % N_RETIRADAS)
w("```")
w("")
w("> **Si no sale, no oculte nada todavia: pare y reportelo.** Significa que la hoja contra la que")
w("> esta trabajando no es la que se genera del modelo, y entonces el problema no es esta etapa sino")
w("> de que archivo salio la aplicacion.")
w("")

# ---------------------------------------------------------------- ETAPA 7
w("# Etapa 7 — Las reglas")
w("")
w("**Duracion:** 45 minutos. **Aqui esta el valor del sistema.**")
w("")
w("Son %d. Las expresiones completas, sin truncar, en" % len(REGLAS))
w("`docs/sdd/RECONSTRUCCION_EXPRESIONES.md` §2.")
w("")
w("### 7.1 El geofencing, y por que sin `Editable_If` no vale nada")
w("")
w("En `MAN_Mantenimientos.Coordenadas_Cierre_LatLong`:")
w("")
w("```")
w("Initial value:  HERE()")
w("Valid_If:       DISTANCE([Coordenadas_Cierre_LatLong], [OTID].[ActivoID].[Ubicacion_LatLong])")
w("                  <= [OTID].[ActivoID].[TipoActivoID].[RadioGeofencingKm]")
w("Invalid text:   Ubicacion fuera de rango: debe estar junto al activo para cerrar.")
w("Editable_If:    FALSE")
w("```")
w("")
w("**El radio va por tipo, no como literal**, porque una subestacion y un poste SOS no admiten la")
w("misma tolerancia. En la hoja vigente esa columna esta poblada en los 27 tipos; contra celdas en")
w("blanco esta expresion **rechazaria tambien los cierres legitimos**, asi que compruebelo antes de")
w("pegarla:")
w("")
w("```bash")
w('python -c "import openpyxl;s=openpyxl.load_workbook(\'BD/Modelo_Datos_PLANTILLA.xlsx\','
  "read_only=True,data_only=True)['TIP_TiposActivo'];h=[c.value for c in next(s.iter_rows(max_row=1))];"
  "i=h.index('RadioGeofencingKm');v=[r[i] for r in s.iter_rows(min_row=2,values_only=True)];"
  'print(len(v),\'tipos,\',sum(1 for x in v if x not in (None,\'\')),\'con radio\')"')
w("```")
w("")
w("**`PAR_Parametros.RADIO_GEOFENCING_KM` no lo lee esta regla.** Es un valor provisional historico")
w("que sigue en la tabla; si alguien le dice que el radio se cambia ahi, esta describiendo el sistema")
w("anterior.")
w("")
w("**El `Editable_If = FALSE` no es un detalle.** Sin el, el tecnico arrastra el pin del mapa y")
w("cierra desde su casa. La regla existiria, se veria, y no probaria nada.")
w("")
w("Lo mismo en `Precision_GPS`, `UbicacionEscaneo_LatLong` y `FechaHoraEscaneo`.")
w("")
w("> **Y un supuesto que sigue sin verificar, el peor del sistema.** No hay pagina oficial que")
w("> confirme si AppSheet evalua un `Valid_If` sobre una columna con `Editable_If = FALSE`. **Si no lo")
w("> evalua, la regla parece funcionar por no ejercitarse nunca.** Se detecta en la etapa 9.")
w("")
w("### 7.2 El umbral de GPS, entero")
w("")
w("En `MAN_Mantenimientos.CierreConExcepcion`, `App formula`:")
w("")
w("```")
w('OR(ISBLANK(LOOKUP("UMBRAL_GPS", "PAR_Parametros", "ParametroID", "Valor")),')
w('   [Precision_GPS] > LOOKUP("UMBRAL_GPS", "PAR_Parametros", "ParametroID", "Valor"))')
w("```")
w("")
w("**El `ISBLANK` no sobra.** Sin el, si alguien borra la fila del parametro **todos los cierres")
w("salen limpios y nadie se entera**. Con el, falla hacia el lado seguro.")
w("")
w("### 7.3 Retirar el borrado")
w("")
w("*Data -> Tables -> [tabla] -> Are updates allowed*:")
w("")
w("```")
w("OT_OrdenesTrabajo    Updates si · Adds si · Deletes NO")
w("MAN_Mantenimientos   Updates si · Adds si · Deletes NO")
w("```")
w("")
w("**Es la otra mitad del `IsPartOf` de la etapa 5.** La cascada solo es segura porque el")
w("mantenimiento no se puede borrar. Configurar una sin la otra deja la puerta abierta.")
w("")
w("### 7.4 Los filtros de seguridad")
w("")
w("*Data -> Tables -> [tabla] -> Security Filter*. Las dos expresiones estan en la lista de reglas.")
w("")
w("**No son solo control de acceso: son rendimiento.** Sin ellos cada tecnico se descarga el")
w("inventario entero al telefono.")
w("")
w("### COMPROBACION de la etapa 7")
w("")
w("| Que | Como se ve |")
w("|---|---|")
w("| Ninguna en rojo | El panel de errores del editor, vacio |")
w("| `Deletes` quitado | En las dos tablas |")
w("| Las cuatro no editables | `Editable_If = FALSE` en las cuatro de captura |")
w("| El umbral con `ISBLANK` | Leala entera, no de por hecho que se pego bien |")
w("")

# ---------------------------------------------------------------- ETAPA 8
w("# Etapa 8 — Las vistas")
w("")
w("**Duracion:** 30 minutos.")
w("")
w("**Esta guia no especifica las vistas, y conviene saberlo antes de abrir la etapa.** El modelo")
if INTERFAZ:
    w("declara ahora %s en `scripts/modelo_objetivo.py`: **actualice este generador**, porque la etapa"
      % " y ".join("`%s`" % n for n in INTERFAZ))
    w("sigue escrita como si no existieran.")
else:
    w("declara datos, no interfaz: `VISTAS`, `ACCIONES` y `SLICES` **no existen** en")
    w("`scripts/modelo_objetivo.py` —comprobado al generar esta guia, no de memoria—. De las etapas")
    w("anteriores puede fiarse porque salen del modelo; de esta no, porque no hay de donde sacarla.")
w("")
w("**Lo unico que AppSheet crea solo son las columnas virtuales `Related ...`**, que aparecen al poner")
w("las referencias de la etapa 5 y traen con ellas la navegacion padre-hijo: al abrir un mantenimiento")
w("se ven sus fotografias y su firma; al abrir un activo, sus ordenes. **Eso es todo lo que se")
w("construye solo.** Las pantallas no.")
w("")
w("**Y las pantallas no se configuran a ojo.** Las tres de abajo van con el tipo y la tabla que dice")
w("la tabla; si algo no encaja, **no lo improvise: anotelo como pendiente y siga**. Una vista")
w("inventada aqui es configuracion activa que nadie declaro, y quien reconstruya la aplicacion no")
w("podra reproducirla.")
w("")
w("### El caso que engana")
w("")
w("**`USR_Usuarios` recibe tres referencias desde `OT_OrdenesTrabajo`** —tecnico, supervisor y quien")
w("cerro— y AppSheet crea tres columnas virtuales con nombres casi iguales. Hay que abrirlas y leer el")
w("segundo argumento del `REF_ROWS` para saber cual es cual.")
w("")
w("**Si solo aparece una, faltan dos y el supervisor no vera sus ordenes.**")
w("")
w("### Las tres pantallas principales")
w("")
w("| Vista | Tipo | Sobre | Nota |")
w("|---|---|---|---|")
w("| Mapa de activos | `Map` | `ACT_Activos` | Columna de mapa: `Ubicacion` |")
w("| Mis ordenes | `Deck` | `OT_OrdenesTrabajo` | Es la pantalla de trabajo del tecnico |")
w("| Mantenimientos | `Table` | `MAN_Mantenimientos` | |")
w("")
w("> **Esta etapa es la menos especificada de todas.** El modelo describe datos, no pantallas: no hay")
w("> declaracion de vistas, acciones ni slices. Lo que haga aqui, **anotelo**, porque es la unica")
w("> constancia que va a quedar.")
w("")

# ---------------------------------------------------------------- ETAPA 9
w("# Etapa 9 — Probar")
w("")
w("**Duracion:** 1 hora. **No se salte esta etapa: es la que dice si algo de lo anterior sirve.**")
w("")
w("La tanda completa esta en `docs/sdd/PRUEBA-003-despliegue.md`. Aqui las cinco que no se negocian.")
w("")
w("### 9.1 La cadena navega")
w("")
w("En el Asistente, las dos expresiones de la etapa 5. **En verde las dos.**")
w("")
w("### 9.2 El cierre legitimo se acepta, y el lejano se rechaza")
w("")
w("Abra un mantenimiento cuyo cierre este junto a su activo: **debe guardar**. Abra otro que este")
w("lejos: **debe rechazarlo** con el mensaje.")
w("")
w("> **Si los dos salen aceptados, no celebre: sospeche.** La causa mas probable es que el `Valid_If`")
w("> no se evalua sobre una columna con `Editable_If = FALSE`, y entonces el geofencing es decorativo.")
w("> Reportelo antes de seguir.")
w("")
w("> **Y con el inventario completo, el radio por tipo es lo que hace la prueba significativa.** Sobre")
w("> los 334 activos repartidos por el corredor, un literal de 1 km mete **7,4 activos de media dentro")
w("> de cada geofence** —la prueba pasaria estando frente al equipo equivocado—; con el radio por tipo")
w("> de la etapa 7 baja a **1,2**. Por eso el literal no se usa.")
w("")
w("### 9.3 El dato llega a la hoja")
w("")
w("Cree un registro desde la aplicacion y **abra la hoja**. Si no esta ahi, no existe.")
w("")
w("### 9.4 El historico no se puede borrar")
w("")
w("Intente borrar un mantenimiento desde la aplicacion. **El boton no debe aparecer.**")
w("")
w("### 9.5 El barrido de fallos silenciosos")
w("")
w("En el Asistente, escriba esto:")
w("")
w("```")
w('REF_ROWS("OT_OrdenesTrabajo", "Activo")')
w("```")
w("")
w("`Activo` en esa tabla **ya no es la referencia al activo**: es la bandera Si/No. La expresion")
w("apunta a la columna equivocada y devuelve lista vacia.")
w("")
w("**Si el Asistente la ACEPTA, anotelo con su texto literal.** Es la prueba de que un despliegue")
w("verde no distingue esa expresion de la correcta. **Sin verla aceptada, no sabemos si el resto paso")
w("por diligencia o por casualidad.**")
w("")

# ---------------------------------------------------------------- ETAPA 10
w("# Etapa 10 — Publicar")
w("")
w("*Manage -> Deploy -> Run deployment check*, y despues **Move app to Deployed state**.")
w("")
w("> ## No publique todavia")
w(">")
w("> **Las coordenadas de los activos no son reales.** De los **368** de la hoja vigente, **34**")
w("> comparten `4.728512, -74.114531`, que esta en Bogota, y los **334** restantes llevan coordenada")
w("> propia pero **calculada sobre el trazado del corredor, no medida en campo**.")
w(">")
w("> Con radios de 0,05 km en la mayoria de los tipos, **el primer tecnico en via no podra cerrar ni")
w("> una orden**. Y se descubre con el tecnico delante.")
w(">")
w("> Es la decision **D-01** y es trabajo de campo. Hasta que llegue, la aplicacion se prueba pero no")
w("> se despliega.")
w("")
w("**Y si existe una aplicacion anterior sobre la misma hoja, despubliquela antes.** Dos aplicaciones")
w("sobre un backend sin integridad referencial corrompen en silencio: la vieja conserva permisos que")
w("el modelo nuevo ya no concede.")
w("")
w("> **El paso 10 es el punto de no retorno.** Todo lo anterior se abandona sin coste. Compruebe la")
w("> etapa 9 entera **antes** de despublicar nada.")
w("")

# ---------------------------------------------------------------- ACTA
w("---")
w("")
w("# Acta — para rellenar al terminar")
w("")
w("**No lo de por cerrado usted.** Este proyecto tiene tres cierres reportados que no resistieron la")
w("comprobacion contra el archivo.")
w("")
w("```")
w("Etapa 0   copia hecha ............................ [  ]   nombre del archivo:")
w("          pestanas ocultas ....................... [  ]   cuantas: ")
w("          verificar_faseA.py ..................... [  ]   salida:")
w("")
w("Etapa 2   tablas dadas de alta ................... [  ]   cuantas de %d:" % len(MODELO))
w("          duplicadas ............................. [  ]   cuales:")
w("")
w("Etapa 3   claves simples y Text .................. [  ]   cuantas de %d:" % len(MODELO))
w("          alguna compuesta ....................... [  ]   cual:")
w("")
w("Etapa 5   referencias puestas .................... [  ]   cuantas de %d:" % N_REF)
w("          IsPartOf ............................... [  ]   cuantas de %d:" % N_PART)
w("          MAN.OTID desmarcado .................... [  ]")
w("          [OTID].[ActivoID].[Ubicacion_LatLong] .......... [  ]   salida:")
w("          [OTID].[TecnicoID].[Correo] ............ [  ]   salida:")
w("")
w("Etapa 6   RETIRADA. No se ejecuta: la hoja vigente no trae columnas que ocultar")
w("          F-19 en verde .......................... [  ]   salida:")
w("")
w("Etapa 7   reglas puestas ......................... [  ]   cuantas de %d:" % len(REGLAS))
w("          Deletes quitado en OT y MAN ............ [  ]")
w("          umbral con ISBLANK ..................... [  ]")
w("")
w("Etapa 9   cierre cercano aceptado ................ [  ]")
w("          cierre lejano rechazado ................ [  ]")
w("          dato leido en la hoja .................. [  ]")
w("          borrado no disponible .................. [  ]")
w('          REF_ROWS(...,"Activo") ................. [  ]   que dijo:')
w("")
w("Errores en rojo que aparecieron, con su texto literal:")
w("")
w("")
w("Cosas que no salieron como dice esta guia:")
w("")
w("```")
w("")
w("---")
w("*Generado de `scripts/modelo_objetivo.py` por `scripts/generar_guia_funcional.py`.*")

salida = os.path.join(RAIZ, "docs", "GUIA_IMPLEMENTACION_FUNCIONAL.md")
with open(salida, "w", encoding="utf-8") as f:
    f.write("\n".join(L) + "\n")
print("Generado:", salida)
print("%d etapas · %d tablas · %d referencias · %d IsPartOf · %d reglas"
      % (10, len(MODELO), N_REF, N_PART, len(REGLAS)))
