# -*- coding: utf-8 -*-
"""Genera docs/ENTREGA_TECNICA_SGMC.md desde el modelo."""
import sys, os
RAIZ = r"D:\@Proyect\Sisga"
sys.path.insert(0, os.path.join(RAIZ, "scripts"))
from modelo_objetivo import MODELO, GRUPOS, REGLAS, RETIPADOS, PROPUESTAS

L = []
w = L.append
w("# Entrega tecnica — reconstruccion del SGMC en AppSheet")
w("")
w("**Este es el documento de entrada.** Dice que hay, en que estado, y el paso a paso para")
w("terminarlo. Todo lo demas son anexos.")
w("")
w("| | |")
w("|---|---|")
w("| Sistema | Gestion de Mantenimiento en Campo · Concesion Transversal del Sisga |")
w("| Backend | Google Sheets `1a4MmZ0u9sNgWmyiR2OPJo9YuUEKJFftbJWMW-KbITRc` |")
w("| Fuente del modelo | `scripts/modelo_objetivo.py` — **unica**. Los documentos se generan de ahi |")
w("| Fecha | 2026-08-09 |")
w("")
w("## Lo primero, en tres frases")
w("")
w("**La hoja esta bien y la aplicacion esta desfasada.** El modelo de datos se corrigio en el")
w("Sheets —27 columnas renombradas, 8 tablas nuevas, 45 campos retirados— y AppSheet conserva")
w("todavia el esquema anterior.")
w("")
w("**No se arregla con `Regenerate`.** La documentacion de AppSheet dice que al regenerar *combina*")
w("la informacion nueva con la existente y **mantiene las columnas viejas**. Lo comprobamos: la tabla")
w("de ordenes sobrevivio a varios `Regenerate` con sus nombres de antes.")
w("")
w("**El procedimiento es borrar cada tabla y volver a darla de alta**, y despues reponer la capa de")
w("expresiones desde una lista escrita. Lo indica el propio AppSheet: *Delete and re-add the table")
w("to create the column structure*.")
w("")
w("---")
w("")
w("## 1. Que leer, y en que orden")
w("")
w("| # | Documento | Para que |")
w("|---|---|---|")
w("| 1 | [`FUNCIONAL_SGMC.md`](FUNCIONAL_SGMC.md) | Que hace el sistema, para quien y por que. **Su §6 es el registro de decisiones**: una sola forma por proposito |")
w("| 2 | [`bd.md`](bd.md) | Diccionario de datos As-Built. **Generado del archivo**: la unica forma de que mienta es que mienta la hoja |")
w("| 3 | [`sdd/RECONSTRUCCION_EXPRESIONES.md`](sdd/RECONSTRUCCION_EXPRESIONES.md) | La lista de reposicion: 27 nombres viejos, 20 reglas, 28 claves, 15 retipados |")
w("| 4 | [`sdd/ESPEC-002-cableado-en-appsheet.md`](sdd/ESPEC-002-cableado-en-appsheet.md) | El detalle del cableado de referencias, con sus 17 pruebas |")
w("| 5 | [`BASE_CONOCIMIENTO_APPSHEET.md`](BASE_CONOCIMIENTO_APPSHEET.md) | 11 comportamientos de la plataforma verificados contra la fuente, con su URL |")
w("| 6 | [`CONTEXTO_OPERACION.md`](CONTEXTO_OPERACION.md) | Como se mantiene el corredor de verdad. De donde sale el modelo |")
w("")
w("**Si solo lee uno, que sea el 3.** Es la lista contra la que se valida el trabajo.")
w("")
w("## 2. El modelo de datos")
w("")
w("**%d tablas.** La fuente es `scripts/modelo_objetivo.py`; este inventario sale de ahi." % len(MODELO))
w("")
for g in GRUPOS:
    tablas = [(t, d) for t, d in sorted(MODELO.items()) if d.get("grupo") == g]
    if not tablas:
        continue
    w("### %s" % g)
    w("")
    w("| Tabla | Columnas | Proposito |")
    w("|---|---|---|")
    for t, d in tablas:
        prop = d["proposito"].replace("\n", " ")
        if len(prop) > 105:
            prop = prop[:103] + "..."
        nueva = " · **nueva**" if d.get("nueva") else ""
        w("| `%s`%s | %d | %s |" % (t, nueva, len(d["columnas"]), prop))
    w("")
w("### Como se regenera la documentacion")
w("")
w("```bash")
w('python scripts/generar_diccionario_bd.py "BD/Modelo de Datos (N).xlsx"')
w("```")
w("")
w("**Nada se documenta a mano.** El diccionario anterior decia 24 hojas cuando habia 32 y describia")
w("columnas renombradas dos dias antes. Por eso se genera.")
w("")
w("## 3. El procedimiento, paso a paso")
w("")
w("### Antes de empezar")
w("")
w("1. **Respaldo del Sheets.** Nombrelo con la fecha.")
w("2. **Anote la version actual de la app.** Es el punto de retorno.")
w("3. **Que nadie use la aplicacion ni edite la hoja** mientras dure. La reversion solo es limpia si")
w("   nadie escribe.")
w("4. **Descargue la hoja a `BD/`** y ejecute la verificacion de partida:")
w("")
w("```bash")
w('python scripts/verificar_faseA.py "BD/Modelo de Datos (N).xlsx"   # debe decir FASE A CERRADA')
w("python scripts/validar_modelo.py                                  # debe dar 0 errores")
w("```")
w("")
w("### Paso 1 — Limpieza")
w("")
w("Borre de AppSheet las tablas que el modelo ya no contempla: `GPS`, `SEC_Secciones` y las")
w("`FRM_SOS` / `FRM_CCTV` / `FRM_PMVF` individuales.")
w("")
w("**Borrar la tabla en AppSheet no borra la hoja.** El dato se queda.")
w("")
w("> **Ojo con `FRM_CCTV` y `FRM_PMVF`:** tienen 15 preguntas cada una que **nunca se migraron** a")
w("> `FRM_Preguntas`, que solo tiene las 15 de `FRM_SOS`. Son 30 preguntas que hay que migrar antes")
w("> o despues. No es bloqueante, pero no se puede olvidar.")
w("")
w("### Paso 2 — Borrar y volver a dar de alta cada tabla")
w("")
w("**Una por una.** Si AppSheet infiere mal una clave, hay que saber en cual.")
w("")
w("```")
w("menu triple punto -> Delete        +  -> Add data -> la hoja -> la pestana")
w("```")
w("")
w("**Y sin parar entre las dos.** Mientras la tabla no existe, todo lo que la referencia grita mas")
w("fuerte: es ruido temporal.")
w("")
w("**El orden importa: de abajo hacia arriba.** Una tabla con errores desaparece para las que la")
w("referencian, asi que empezando por arriba parece que no se avanza.")
w("")
w("```")
w("1. Catalogos      CAL_Calzadas · SEN_Sentidos · EST_Activo · FRE_Frecuencias")
w("                  TPR_TiposRespuesta · ROL_Roles · SED_Sedes · UNF_UnidadesFuncionales")
w("                  EOT_EstadosOrden · MOT_MotivosPendiente · FAL_ModosFalla · PAR_Parametros")
w("2. Formularios    FRM_Formularios · FRM_Secciones · FRM_Preguntas · LST_ValoresLista")
w("3. Maestras       TIP_TiposActivo · USR_Usuarios · ASG_AsignacionZona")
w("4. Activos        ACT_Activos")
w("5. Ordenes        OT_OrdenesTrabajo · PLA_PlanMantenimiento · NOV_Novedades")
w("6. Ejecucion      MAN_Mantenimientos · CHK_Checklists · CHD_ChecklistDetalle")
w("                  FOT_Fotografias · FIR_Firmas")
w("```")
w("")
w("### Paso 3 — Las claves, en la misma sesion")
w("")
w("**Esto es lo unico que no se puede recuperar despues.** Al dar de alta una tabla, AppSheet elige")
w("clave por su cuenta: examina las columnas de izquierda a derecha y, **si ninguna le sirve, combina")
w("dos en una clave compuesta**. Contra una clave compuesta no resuelve ninguna referencia.")
w("")
w("| Tabla | Clave | Tipo |")
w("|---|---|---|")
for t, d in sorted(MODELO.items()):
    pk = [c["nombre"] for c in d["columnas"] if c.get("pk")]
    if pk:
        w("| `%s` | `%s` | `Text` |" % (t, pk[0]))
w("")
w("**Todas `Text`, sin excepcion.** El caso que lo justifica es `USR_Usuarios.UsuarioID`: tiene un")
w("valor `3aa202ee` entre diez numericos. Si AppSheet infiere `Number`, esa fila queda sin clave")
w("valida y su usuario deja de existir para el sistema.")
w("")
w("**Una sola casilla `KEY` por tabla.** Si quedan dos, quite la sobrante.")
w("")
w("### Paso 4 — Generacion de clave para filas nuevas")
w("")
w("Sin esto la aplicacion no sabe que identificador poner al crear un registro.")
w("")
w("| Tabla | Columna | `Initial value` |")
w("|---|---|---|")
for t in ("MAN_Mantenimientos", "FOT_Fotografias", "FIR_Firmas", "CHK_Checklists",
          "CHD_ChecklistDetalle", "NOV_Novedades"):
    pk = [c["nombre"] for c in MODELO[t]["columnas"] if c.get("pk")]
    if pk:
        w("| `%s` | `%s` | `UNIQUEID()` |" % (t, pk[0]))
w("")
w("### Paso 5 — Las referencias")
w("")
w("**%d columnas pasan de texto o numero a `Ref`.** Primero la clave del destino, despues quien la"
  % sum(len(m) for m in RETIPADOS.values()))
w("apunta.")
w("")
w("| Tabla | Columna | Hoy | `Ref` a |")
w("|---|---|---|---|")
for t, m in RETIPADOS.items():
    for c, d in m.items():
        w("| `%s` | `%s` | %s | `%s` |" % (t, c, d[0], d[2]))
w("")
w("**Convertir `Text` a `Ref` conserva solo las filas cuyo valor coincide con la clave del destino.**")
w("Las demas quedan huerfanas **sin mensaje de error**: la celda se queda en blanco. Despues de cada")
w("conversion, mire si aparecieron blancos donde habia valores.")
w("")
w("**Se valida en el Asistente de Expresiones, no ejercitando la aplicacion.** La que sostiene el")
w("geofencing es esta:")
w("")
w("```")
w("[OTID].[ActivoID].[Ubicacion]")
w("```")
w("")
w("Si el asistente la rechaza, pare.")
w("")
w("### Paso 6 — Reponer las reglas")
w("")
w("**%d reglas.** Estan en [`sdd/RECONSTRUCCION_EXPRESIONES.md`](sdd/RECONSTRUCCION_EXPRESIONES.md)"
  % len(REGLAS))
w("§2 con su expresion completa. Aqui solo el mapa:")
w("")
w("| # | Tabla | Columna | Tipo |")
w("|---|---|---|---|")
for r in REGLAS:
    w("| %s | `%s` | `%s` | %s |" % (r.get("id", ""), r.get("tabla", ""),
                                     r.get("columna", "(tabla)"), r.get("tipo", "")))
w("")
w("**Cuatro no se pueden ejecutar en el plan gratuito** — las de tipo Bot y Bot programado. Se dejan")
w("escritas y se activan cuando se decida el licenciamiento.")
w("")
w("### Paso 7 — Verificar")
w("")
w("**No se declara cerrado por el reporte de quien lo hizo.** Este proyecto tiene tres cierres")
w("reportados que no resistieron la comprobacion contra el archivo, y las tres veces lo paro un")
w("script.")
w("")
w("```bash")
w("python scripts/validar_modelo.py                                  # el modelo consigo mismo")
w('python scripts/verificar_faseA.py "BD/Modelo de Datos (N).xlsx"   # el modelo contra la hoja')
w("python scripts/verificar_documentos.py                            # la prosa contra el modelo")
w("```")
w("")
w("Y las **17 pruebas de aceptacion** de [`sdd/PRUEBA-002-cableado-en-appsheet.md`](sdd/PRUEBA-002-cableado-en-appsheet.md),")
w("con sus cuatro innegociables: `P-05`, `P-09`, `P-12` y `P-16`.")
w("")
w("## 4. Lo que NO cabe en el plan gratuito")
w("")
w("No es mas adelante: es **no en el plan actual**. Solo cambia con la decision de licenciamiento.")
w("")
w("| Lo que se querria | Por que no |")
w("|---|---|")
w("| Generacion automatica de las ordenes del mes | Los procesos programados no se ejecutan |")
w("| Aviso al supervisor de que hay trabajo por recibir | Lo mismo |")
w("| Integracion con el SCADA para abrir correctivas | Sin plan Core no hay API REST |")
w("| Atributos distintos por tipo de equipo | El backend es una hoja: no hay esquema dinamico |")
w("| Que una escritura directa en la hoja respete las validaciones | Imposible por diseno |")
w("")
w("**Y el volumen:** AppSheet degrada por encima de ~50.000 filas por tabla. Con el inventario real")
w("`CHD_ChecklistDetalle` llega a 143.700 filas en cinco anos. **Archivar por ano no es opcional.**")
w("")
w("## 5. Lo que viene despues, y no esta construido")
w("")
w("**%d tablas propuestas**, especificadas en `ESPEC-003` y pendientes de que su bloqueo se levante:"
  % len(PROPUESTAS))
w("")
w("| Tabla | Para que |")
w("|---|---|")
for t, (motivo, donde) in sorted(PROPUESTAS.items()):
    m = motivo.replace("\n", " ")
    if len(m) > 95:
        m = m[:93] + "..."
    w("| `%s` | %s |" % (t, m))
w("")
w("**La mas importante es `TAR_Tareas`.** Hoy el modelo asume que un activo tiene *una* frecuencia y")
w("un tipo tiene *un* formulario. En la operacion real un poste SOS tiene prueba semanal, prueba")
w("mensual con interventoria y mantenimiento trimestral. **La periodicidad es de la tarea, no del")
w("activo.**")
w("")
w("## 6. Reglas de trabajo del proyecto")
w("")
w("Estan en `CLAUDE.md`. Las tres que mas han evitado desastres:")
w("")
w("**No se declara nada conforme por reporte. Se verifica contra el archivo, y se dice contra cual.**")
w("")
w("**Quien aplica un cambio no toca la comprobacion que lo mide.** Si una validacion estorba, se")
w("endurece o se sustituye por la inversa; no se retira.")
w("")
w("**Una sola forma por proposito.** Antes de proponer un mecanismo, se comprueba si ya existe uno")
w("—`FUNCIONAL_SGMC.md` §6—. Si el nuevo es mejor, se retira el viejo en el mismo cambio.")
w("")
w("---")
w("*Documento generado de `scripts/modelo_objetivo.py`. Para actualizarlo, cambie el modelo y vuelva*")
w("*a generar.*")

salida = os.path.join(RAIZ, "docs", "ENTREGA_TECNICA_SGMC.md")
with open(salida, "w", encoding="utf-8") as f:
    f.write("\n".join(L) + "\n")
print("Generado:", salida)
print("%d tablas, %d reglas, %d propuestas, %d retipados"
      % (len(MODELO), len(REGLAS), len(PROPUESTAS), sum(len(m) for m in RETIPADOS.values())))
